version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: container-postgresql-demo
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - demo-network

networks: 
  demo-network:
    driver: bridge
