version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: container-postgresql-demo
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data/pgdata
    networks:
      - demo-network

  mongodb:
    image: mongo
    container_name: container_mongodb_demo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
        - ./.docker/mongodb/db:/data/db
    command: mongod --auth
    ports:
      - 27017:27017
    networks:
      - demo-network

  redis:
    image: redis:alpine
    container_name: container_redis_demo
    restart: always
    #environment: 
    volumes:
      - ./.docker/redis/data:/data
    command: redis-server --requirepass RedisPassword2020!
    ports:
      - 6379:6379
    networks: 
      - demo-network

networks: 
  demo-network:
    driver: bridge
